// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///

namespace Cookieclicker2mp4Google
{
public static class GPGSIds
{
        public const string achievement_10_autoclickers = "CgkIleno69UVEAIQAw"; // <GPGSID>
        public const string leaderboard_cps = "CgkIleno69UVEAIQBQ"; // <GPGSID>
        public const string leaderboard_cookies = "CgkIleno69UVEAIQAg"; // <GPGSID>
        public const string achievement_10_drills = "CgkIleno69UVEAIQBw"; // <GPGSID>
        public const string achievement_bake_a_cookie = "CgkIleno69UVEAIQAQ"; // <GPGSID>
        public const string achievement_10_grandmas = "CgkIleno69UVEAIQCA"; // <GPGSID>
        public const string achievement_10_cookie_factorys = "CgkIleno69UVEAIQCQ"; // <GPGSID>
        public const string leaderboard_cpc = "CgkIleno69UVEAIQBg"; // <GPGSID>
        public const string achievement_10_doublecookies = "CgkIleno69UVEAIQBA"; // <GPGSID>

}
}
